### ISSUE TITLE
BehaviorSubject declared with .startWith() returns the initial value instead of the latest value.

### ISSUE THREAD

**Issue by dotdotcommadot** [ReactiveX/rxdart#112]
A BehaviorSubject declared with .startWith() will return the initial value instead of the latest value.
But using the `seedValue`property it seems to work correctly.
I would expect `.startWith()` to act similar as when using the `seedValue` property. 
Let's have a look at following examples:

**Example 1**
- sets seedValue: 0
```
rx.BehaviorSubject<int> countController = new rx.BehaviorSubject<int>(seedValue: 0);

new rx.Observable(document.onKeyUp)
    .doOnData((_) => print('KEY UP'))
    .flatMapLatest((_) => countController.stream.take(1))
    .map((int curr) => curr + 1)
    .listen((int curr) => countController.add(curr));

new rx.Observable(countController.stream)
   .listen(print);
```
This results in: 
```
0 // (—> This one triggers when listening to the BehaviorSubject of course)
KEY UP
1
KEY UP
2
KEY UP
3
```
**Example 2**
- has no seedValue
- has a ‘count’ Observable wich sets .startWith(0)
```
rx.BehaviorSubject<int> countController = new rx.BehaviorSubject<int>();
rx.Observable count = countController.stream.startWith(0);

new rx.Observable(document.onKeyUp)
    .doOnData((_) => print('KEY UP'))
    .flatMapLatest((_) => count.take(1))
    .map((int curr) => curr + 1)
    .listen((int curr) => countController.add(curr));

new rx.Observable(countController.stream)
    .listen(print);
```
This results in: 
```
KEY UP
1
KEY UP
1
KEY UP
1
```

Just as in example 1, I would expect example 2 to just increment the counter on each keystroke.

**Comment by brianegan** [comment]
Hey, I looked at this a bit, and I think this would be tough to fix until Dart 2.0 Streams come around :(

Our `BehaviorSubject` class uses a bit of a workaround: It uses `DeferStream` under the hood, which creates a new Stream every time you listen to it. Unfortunately, this is the only way we've found to send the initial data event to new `listeners`.

Knowing that it recreates the stream each time, you might see why the code in your second example always starts at 0: Because `startWith` is always sending the 0 first in the `take(1)`!

Luckily, there are a couple of changes you could make: Use `seedValue` exclusively, or rearrange your code a bit so it works like this, which uses the `scan` operator (probably a more idiomatic way of doing what you're trying to accomplish):

```
  final controller = new BehaviorSubject<int>();
  final count = new Observable(document.onKeyUp)
      .map((_) => 1) // Convert the `keyUp` to an integer
      .scan((acc, val, i) => acc + val, 0) // Use the scan operator starting with 0!
      .listen(controller.add);

  controller.stream.listen(print);
```

With Dart 2.0, being able to properly multicast streams will hopefully fix the underling issue that causes us to use this workaround.
