### ISSUE TITLE
Stream field in Observable class is now private

### ISSUE THREAD

**Issue by long1eu** [ReactiveX/rxdart#158]
Is there a reason why the stream field is now private? I want to extend from the Observable class but I can't pass the stream in initialiser since my StreamController can't be static so I only have my stream at the end of the constructor body. To make this work I override the stream field and pass it the stream from my controller.

**Comment by long1eu** [comment]
My current workaround this is this.

```
  factory ObservableSocketIOClient(String uri, Map<String, String> queryParams, String path) {
    final Socket socket = Io.socket(
      uri,
      new ManagerOptions(
        transports: const <String>[WebSocket.NAME],
        reconnection: false,
        timeout: 3000,
        query: queryParams,
        path: path,
      ),
    );

    final StreamController<SocketEvent> controller = new StreamController<SocketEvent>.broadcast();

    return new ObservableSocketIOClient._(socket, controller);
  }

  ObservableSocketIOClient._(this.socket, StreamController<SocketEvent> controller)
      : _controller$ = controller,
        super(controller.stream) {
    _controller$.onListen = _onListen;
    _controller$.onCancel = _onCancel;
  }
```

**Comment by brianegan** [comment]
Overall, it felt like something a subclass shouldn't be overriding (since dynamically switching the Stream could lead to unexpected results from the call side), and the change helped us simplify some code in our Subject implementation which also extend `Observable`, but looks like it had negative impacts on the community.

I'll be honest: I assumed folks were already taking the path you're using in your second comment, which is a common pattern for extending any class that has `final` variables where you need to do some additional setup work before calling the `super` constructor. You can see the `BehaviorSubject` implementation as another example.

This is one of those odd corners of the Dart language that makes extending classes a bit difficult to work with.

@frankpepermans What do you think? It feels a bit weird to override a `final` variable with a function that could return any Stream. It seems to go against the API design of the Observable class, where `_stream` is final for a good reason, but it does make extending a bit more awkward if you were explicitly overriding that value.

**Comment by frankpepermans** [comment]
From an API standpoint, having a public ```stream``` property is confusing,
but I understand the OP's problem.

I'd say make it public again, but let's annotate with ```@protected``` for example from the meta package.

This way we kind of make it clear that the public ```stream``` property is availabe for etending classes, but not for common usage in code?

**Comment by long1eu** [comment]
My concern is mainly about fallowing Dart convention. So if my workaround is the actual way to do it, then I'm totally fine to be it private, especially if I take into account @brianegan points.

**Comment by brianegan** [comment]
Sounds good. If you're cool with it, I think it makes sense to go forward with keeping _stream private for the reasons discussed in this thread!
