### ISSUE TITLE
Schedulers/TestScheduler

### ISSUE THREAD

**Issue by qwilbird** [ReactiveX/rxdart#171]
Hi RxDart team,

awesome work! Are you currently considering adding more schedulers to rxDart and also a way to test them?
As a reference, I am thinking of the schedulers and testScheduler in [RxJs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/testing/testscheduler.md).

Thank you!

**Comment by brianegan** [comment]
Hey hey :)

Ah schedulers, the eternal question. It's a bit of a funny one in RxDart, since Dart Streams already have `sync` vs async mechanisms when create a StreamController. Therefore, in some sense, Stream classes already have their own semantics around "Schedulers." We've explored the options a bit, but need to take more time to come up with something that feels right.

For testing, I recommend using two things:

  1. StreamMatchers from the test package: https://pub.dartlang.org/packages/test#stream-matchers. In many cases, especially if you're using Mock data sources, these will run very quickly and there's no need for a TestScheduler from my experience.

  2. If you need to test time-based stuff, such as `debounce` logic, you can use the Quiver package's FakeAsync utilities. An example can be seen here: https://github.com/escamoteur/making_flutter_reactive-/blob/master/test/homepage_model_test.dart#L39

Therefore, I'd say you should be able to test everything just fine at the moment, but we need to consider proper schedulers a bit more and see if we can make them work and feel right.

**Comment by brianegan** [comment]
Hey all,

I've attempted to make schedulers a thing for RxDart, but I'm really not sure it will work out.

  1. Streams are already "scheduled" sync or async by the Stream api via `StreamController(sync: true / false)`. And that scheduling can turn from `sync` to `async` in funny ways based on the ways Streams buffer events under the hood!
  2. Something like an `IsolateScheduler` would be amazing! Schedule some work on a background isolate, then return back to the main isolate. Unfortunately, the way the Isolate API works, after a lot of trial and error, I don't think we can actually make this type of Scheduler happen in a way that would provide much benefit.
  3. We could consider a `TestScheduler` as well. I think we could make this one work, but I'm not sure it will be any more convenient to use than the `FakeAsync` utils from Quiver. In fact, that library is more powerful because it's not restricted to only streams!

Overall, while I think it would be cool to add Schedulers, I do not think we should implement schedulers at this point for RxDart for the above reasons.
