### ISSUE TITLE
Using myStream$.take(1) in CombineLatest() will always return very first value from myStream$

### ISSUE THREAD

**Issue by dotdotcommadot** [ReactiveX/rxdart#181]
**What it does**
Using myStream$.take(1) in a CombineLatest() will always return the very **first** value from myStream$.

**What I expect it to do**
Using myStream$.take(1) in a CombineLatest() should retrieve the **latest** value from myStream$

**Example One**
```
final BehaviorSubject<int> counterController =
    new BehaviorSubject<int>(seedValue: 0);
final Observable<bool> timer$ =
    new Observable<bool>.periodic(new Duration(seconds: 1), (_) => true)
        .asBroadcastStream();

Observable.combineLatest2(timer$, counterController.stream.take(1),
        (_, int counter) => counter + 1)
    .doOnData(counterController.add)
    .listen((int counter) => print('CombineLatest() $counter'));
```
==> This will always print `CombineLatest() 1`, while I would expect it to increment the number

**Example Two: Comparison to using SwitchMap()**
```
final BehaviorSubject<int> firstCounterController =
    new BehaviorSubject<int>(seedValue: 0);
final BehaviorSubject<int> secondCounterController =
    new BehaviorSubject<int>(seedValue: 0);
final Observable<bool> timer$ =
    new Observable<bool>.periodic(new Duration(seconds: 1), (_) => true)
        .asBroadcastStream();

Observable.combineLatest2(timer$, firstCounterController.stream.take(1),
        (_, int counter) => counter + 1)
    .doOnData(firstCounterController.add)
    .listen((int counter) => print('CombineLatest() $counter'));

timer$
    .switchMap((_) => secondCounterController.take(1))
    .map((int counter) => counter + 1)
    .doOnData(secondCounterController.add)
    .listen((int counter) => print('SwitchMap() $counter'));
```
==> This will print:
```
CombineLatest() 1
SwitchMap() 1
CombineLatest() 1
SwitchMap() 2
```

**Comment by frankpepermans** [comment]
Ah, the take operator, or take one in this case does the following:

Emit the next event (1) and then close the Stream.

When you use combineLatest like in example one, the only remaining trigger firing is your timer Stream.

But the count value will always be the same, that single value you took from it.

So the add on doOnData here has also no effect, since the TakeStream is already closed

**Comment by frankpepermans** [comment]
Your second example works, because when the TimerStream fires, you have switchMap, which effectively creates a new TakeStream, returning the next one event.

Since you later add to the controller, this next one event is always the latest value.

If you seek to create a Stream which carries an index on a Timer, try a Stream.periodic, or maybe an async* with yield generator?

**Comment by dotdotcommadot** [comment]
Ow, I see...
It feels a bit counter-intuitive (to me), but I do get the logic behind it of course.

Thanks!
