### ISSUE TITLE
[Enhancement] Has ‘IsolateSingleScheduler’ ‘IsolateMainScheduler’ ‘IsolateIOScheduler’ like in rxdart?

### ISSUE THREAD

**Issue by Guang1234567** [ReactiveX/rxdart#228]
Hello dev:

Has ‘IsolateSingleScheduler’ ‘IsolateMainScheduler’ ‘IsolateIOScheduler’  like in rxdart?

**Comment by frankpepermans** [comment]
Not at this point, sharing code between Isolates is not straightforward in Dart,
But who knows, maybe Dart will support immutable objects over Isolates at some point, then we can consider it :)

**Comment by brianegan** [comment]
Unfortunately, I've tried this a few times but always failed. As @frankpepermans has noted, there's no way to move a Stream from one isolate to another -- it results in an exception. That would be a minimal requirement for this feature to work :/

I'm gonna go ahead and close this for now since we've had a few threads about Schedulers, but I just don't quite think they fit into Dart like they do normal RxJava or RxJS.
