### ISSUE TITLE
Support allowing multiple types in ofType

### ISSUE THREAD

**Issue by naiveai** [ReactiveX/rxdart#298]
It feels a little odd to have an `ofType` function that can only filter a single type. And sure, you can create a class to extend those two types from if you have control over them, but often you don't. Having a list would be a breaking change, but there's also no easy way to implement something like Python's `*args` in Dart. What do you think about it?

**Comment by brianegan** [comment]
Hey there -- interesting proposal! Could you describe your use case a bit more? 

One big question I have: What would `ofType` return in that world? Right now, `ofType` returns an `Observable<TheTypeYouWantToFilter>`. If `ofType` allowed you to filter down to one of many , then `ofType` would need to return an `Observable<dynamic>`, which means you'd lose type information.

`ofType` is built to do two things: Filter the items in an Observable to a specific class, then cast the Stream to be a Stream of that particular class. IMO, if you wanted to filter based on many types, it probably makes more sense to just use the `where` method rather than another operator:

```
Stream<dynamic>.fromIterable([1, "Hi", 4.0]).where((item) {
  return item is String || item is int;
});
```

**Comment by naiveai** [comment]
I'm a massive idiot, of course I could just use a where lol. Where is my head gone these days.
