### ISSUE TITLE
Is there any plans to add Relays?

### ISSUE THREAD

**Issue by MortyMerr** [ReactiveX/rxdart#327]
Relays (PublishRelay/BehaviorRelay like in RxSwift/RxJava) are very useful in a state management and reactive architecture implementation. I have some business logic which doesn't require stream to throw error/complete.
What do you think?

**Comment by MortyMerr** [comment]
BTW, do you have Slack or someplace to for discussions?

**Comment by frankpepermans** [comment]
They're not planned, as we build upon Dart `Streams`, those do not close down when they have an Error (unless `cancelOnError` is true when creating).

So you could just ignore any Errors today, without requiring `Relays`.

Our channel is on Gitter, ReactiveX/RxDart!

**Comment by MortyMerr** [comment]
Thanks, closed 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brianegan** [comment]
Closing this since I do believe this might work better as an extra package / extension -- but one big thing to note that might make relays a bit less necessary: Dart Streams do not automatically terminate when an error is emitted unless you specify `cancelOnError: true` when listening -- which if I remember correctly was one of the main reasons why Jake made RxRelay in the first place -- to prevent an Observable from closing down prematurely due to error event being emitted.
