### ISSUE TITLE
RetryWhenStream retrying unreliably

### ISSUE THREAD

**Issue by daniel-kg** [ReactiveX/rxdart#338]
When running the following code: 

```dart  
    var publisher = ReplaySubject();
    publisher.add('first event');
    Stream<Stream<int>> streamGen(stream) async* {
      print('initialising');
      await for(var event in stream){
        print(event);
        yield Observable.fromIterable([1, 3]);
      }
    }
    var subscription = RetryWhenStream(
        () => streamGen(publisher.stream)
                .asyncExpand((stream) => stream)
                .transform(StreamTransformer.fromBind((stream) async* {
              await for (var val in stream) {
                if (val == 3) {
                  print('throwing');
                  throw AssertionError();
                } else {
                  yield val;
                }
              }
            })), (e, s) {
          print(e);
          print('retrying');
      return Observable.just(null);
    }).listen(print);

    await subscription.asFuture();
```

I receive *only* the output:
```
initialising
first event
1
throwing
```

The retry functionality doesn't take place. The error seems to get lost somewhere? Interestingly if I change the line `publisher.add('first event');` to
```dart
    publisher.add('first event');
    publisher.add('second event');
    publisher.add('third event');
```

The expected behaviour is seen (i.e an infinite loop of retries). 

Interestingly it doesn't happen with just two publisher events... suggesting some bad state somewhere along the line.

Anything to enlighten me on the cause of this buggy looking behaviour would be great!

This is with rxdart==0.22.2 code

**Comment by frankpepermans** [comment]
Hi there,

It seems that the Error which is thrown in `fromBind` doesn't reach the outer Observable,
I was able to fix your example by using `Stream.map` instead of using your generator `Function`:

```
var publisher = ReplaySubject<dynamic>();
  publisher.add('first event');
  Stream<Stream<int>> streamGen(Stream stream) async* {
    print('initialising');
    await for (var event in stream) {
      print(event);
      yield Observable.fromIterable([1, 3]);
    }
  }

  var subscription = RetryWhenStream<dynamic>(
      () => streamGen(publisher.stream)
          .asyncExpand((stream) => stream)
          .transform<dynamic>(StreamTransformer<int, dynamic>.fromBind(
              (Stream<int> stream) => stream.map<int>((event) {
                    if (event == 3) {
                      throw new Error();
                    }

                    return event;
                  }))), (Object e, s) {
    print(e);
    print('retrying');
    return Observable.just(null);
  }).listen(print);

  await subscription.asFuture<dynamic>();
```

I've yet to investigate as to why the `Error` in your snippet is not being forwarded, nevertheless that wouldn't be an RxDart issue, but rather a Dart issue.

Normally when using a `StreamTransformer`, you can access the `Sink` of the transformer, which is where you would add `Errors` so that they can propagate. With fromBind, this scope is not available.

**Comment by brianegan** [comment]
I'd guess it relates to this issue: https://github.com/dart-lang/sdk/issues/33818

Because of that issue, sometimes those async generator functions don't quite work the way you'd expect them to. When transforming Streams, I'd generally recommend you avoid `async*` functions until that issue is resolved (in fact, the example they give in that issue is a StreamTransformer that doesn't work because of the current issue!).

**Comment by brianegan** [comment]
Gonna close this out for now since I don't think we can do anything about this from our side :/
