### ISSUE TITLE
RxDart and extension functions

### ISSUE THREAD

**Issue by rullyalves** [ReactiveX/rxdart#346]
As of Dart 2.6, we have extension functions, so we can add methods to a class from them, it's possible that RXDart will be updated to now allow most operators to be added to the Stream class or StreamBase instead of Observable ?

**Comment by frankpepermans** [comment]
We'll certainly use extension methods, I've yet to run through the spec, but I don't expect there would be issues stopping us:)

**Comment by brianegan** [comment]
Absolutely! I've actually got a branch that takes this idea to a logical extreme: Completely removing the Observable class (which is really just a wrapper Class around a Stream) and replaces it with an Extension class!

https://github.com/ReactiveX/rxdart/tree/extension-methods

Now, that particular branch is a bit of a "though exercise": meaning it would be a very harsh breaking change. That was done on purpose to see what / how much could be cleaned up if we ditch the `Observable` class altogether.

In reality, we should probably make the Extension "Class" a new thing and keep the current Observable class in order to provide end users with a stable transition period, but it's exciting to think about how much we could clean up by taking this path (add 2400 lines, remove 5600).

**Comment by brianegan** [comment]
PR now opened up with initial code for this idea + discussion about how to make this change: #349

**Comment by brianegan** [comment]
Extension method now shipped as part of `0.23.0-dev.1`. Please give me a try and file new issues if you run into trouble :)
