### ISSUE TITLE
Document Stream Spec vs Observable Spec quirks

### ISSUE THREAD

**Issue by brianegan** [ReactiveX/rxdart#71]
This includes:

  * [x] Dart Sync vs Async Streams vs / in combination with Rx Schedulers as we introduce that concept
  * [x] Return type of `first`, `last`, etc returns `Future` not an `Observable`
  * [x] Error contract in Observable (closes stream) vs Dart (does not by default)

**Comment by lestathc** [comment]
Suggestion, may want to mention:
`StreamController onListen` side effect triggering logic is different than `Observable onSubscribe` (for [`create` operator](http://reactivex.io/documentation/operators/create.html)).

Well, `Observable onSubscribe` is not officially documented in ReactiveX that it must be called every time Observable is subscribed, but it is in all existing rx implementations.

But for broadcast stream, the `onListen` is only be called at the first time it is subscribed, so that it is equal to `observable.publish().autoConnect(1)`. (For non-broadcast stream, it is fine since it can not be subscribed multiple times)
