### ISSUE TITLE
Improve "Coming from other Rx implementations" docs

### ISSUE THREAD

**Issue by brianegan** [ReactiveX/rxdart#89]
We've got some docs in the Observable class, but we should create more docs for peeps to get started. Ideas:

  * Creating Observables / Streams
  * Creating / working with Futures for one-off operations, where streams aren't actually necessary (might be good for folks new to Dart who don't know about the async primitives)
  * Working with single-subscription streams
  * Documenting `cancelOnError` patterns

**Comment by adaojunior** [comment]
Thank you for porting rx to dart,
I don't mean to complain, I just want to give you a honest feedback.
My experience so far is that I find rx resources mostly for javascript, but when I try to use on rxdart I just can't get it to work.
I was porting a library that  uses rxjs but it was too difficult because rxdart is so different.

**Comment by frankpepermans** [comment]
Can you share an rxjs snippet you wish to port to rxdart? Would be glad to
help you out here.

**Comment by adaojunior** [comment]
I tried to port this: https://github.com/ngrx/store/blob/master/src/state.ts#L14-L20

But I could not find a replacement for `observeOn` or `queue`.

**Comment by adaojunior** [comment]
I also could not find a replacement for `Observer`.

**Comment by brianegan** [comment]
Thanks for the feedback @adaojunior! Overall, other than the `observeOn` queue, that library you linked to can definitely be replicated using RxDart. I'll try to post up a code sample tonight. That said, I wonder if the name RxDart is confusing, and would love your feedback on this ticket here:

https://github.com/ReactiveX/rxdart/issues/95

**Comment by brianegan** [comment]
Decided to fix the docs but decided not to extend Observable just yet as we plan on renaming the repo, and might change the naming for this just a bit.

**Comment by kentcb** [comment]
Maybe this is obvious to someone who has used Dart for longer than the 1 day I've been using it, but I am confused as to what replaces `Unit` in Rx.NET.

**Comment by frankpepermans** [comment]
Just adding the 'help wanted' label.
With Flutter gaining traction, we see more and more people giving rxdart a try as well.

Please do report how you experienced the transition from rxAny to rxDart
and how may we improve this in the future?

If you would like to share examples, feel free to submit a PR!

**Comment by stanislasdrg** [comment]
> Please do report how you experienced the transition from rxAny to rxDart
and how may we improve this in the future?

I am porting some Angular Ts code and the Auth0 SPA library to Angular Dart. The experience has been much more painful that I initially anticipated. This is mostly because of RxDart's confusing API, which looks like pre RxJs 5, but without some of the methods you are used to.
I understand there are some inherent limitations caused by Dart's Streams, but then, why not even follow Rx 5+ syntax ? Shouldn't the goal be to make it easy for people to try Dart and feel right at home and to port libraries easily ?

**Comment by brianegan** [comment]
Adding this table to the latest version! Thanks again for all the comments and feedback.
